### PR TITLE
feature: Add support for viewing job batches

### PR DESCRIPTION
**Pull request by angu1ss**

### CODE REVIEW

**Comment by angu1ss** [comment]
### Summary of Changes

I have introduced a new model and resource to enhance Noval by displaying not only jobs and failed jobs but also job batches. This aims to provide visibility of batch processing.
I have added English and Russian translations, but I couldn't add German because I don't know it enough.

### Testing Instructions

To test this feature, you can create job batches by following the [Laravel documentation on job batching](https://laravel.com/docs/11.x/queues#job-batching). Once you have created some job batches, you can navigate to the admin panel to view them alongside the existing jobs and failed jobs.

**Comment by angu1ss** [comment]
As the next improvement, I plan to implement a cancel action for job batches, along with introducing cards that display jobs, falillures  .

**Comment by angu1ss** [comment]
As the next enhancement, I plan to implement a cancel action for job batches and introduce cards that display job metrics, including total jobs processed over a period and average attempts per job.

**Review by kaiserkiwi — APPROVED** [review]
Sorry it took me so long. Switched to FilamentPHP for all my projects and lost the focus a bit.

**Comment by kaiserkiwi** [comment]
I fixed a bug afterwards when the specific table doesn't exist. Missed to catch that before the Merge, but saw it in an old project of mine. 

Anyways. Thanks for you pull request. It's part of Release 1.3.0

**Pull request merged**
